version: 2
jobs:
  build:
    docker:
      # CircleCI Go images available at: https://hub.docker.com/r/circleci/golang/
      - image: circleci/golang:1.14.3
    working_directory: /go/src/github.com/hortonworks/salt-bootstrap
    steps:
      - checkout
      - restore_cache:
          keys:
            - pkg-cache
      - run:
          name: Downloading dependencies
          command: make deps
      - run:
          name: Analyzing code
          command: make _check
      - run:
          name: Run unit tests
          command: make test
      - run:
          name: "Building binaries"
          command: make _build
      - save_cache:
          key: pkg-cache
          paths:
            - "/go/pkg"